# bundle exec jekyll serve --livereload

# General settings
site_title: "Desafio JXVII"

# Collections settings
collections:
  levels:
    output: true

# Styles settings
sass:
  sourcemap: never

# Optimization settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: true
  profile: false
  startings: [html, head, body]
sass:
  style: compressed