# bundle exec jekyll serve --livereload

# /wzoyvdvzmj - Código do arqueólogo
# /6ML8KB2J3K - QR Code
# /iyE4C2Jj6I - L2l5RTRDMkpqNkk= (base 64)
# /fA4E3jIUA5 - /pK4O3tSEK5 (cifra de césar) 10
# /15v0FnSMxL
# /n4Tl6175mm

# 01 - ...
# 02 - ...
# 03 - ...
# 04 - ...
# 05 - 
# 06 - F A D A
# 07 - 
# 08 - 
# 09 - 
# 10 - Cifra de César

# 11 - Câmera/Microfone/Pessoa Correndo/Erro/Repetição
# 12 - Código Spotify
# 13 - 
# 14 - QR Code
# 15 - Código do Arqueólogo
# 16 - Invertida
# 17 - 
# 18 - Constelação
# 19 - 
# 20 = 

# 21 - 
# 22 - 
# 23 - Código Spotify
# 24 - 
# 25 - Base 64
# 26 - 
# 27 - 
# 28 - 
# 29 - 
# 30 - Código do Arqueólogo

# 31 - 
# 32 - 
# 33 - 
# 34 - 
# 35 - 
# 36 - Acróstico
# 37 - 
# 38 - 
# 39 - 
# 40 -

# 41 - 
# 42 - 
# 43 - 
# 44 - 


# General settings
site_title: "Desafio JXVII"

# Collections settings
collections:
  levels:
    output: true
  videos:
    output: true

# Styles settings
sass:
  sourcemap: never

# Optimization settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: true
  profile: false
  startings: [html, head, body]
sass:
  style: compressed